### ISSUE TITLE
[Bug] Wired issue about Fibonacci example

### ISSUE THREAD

**Issue by WMXPY** [jterrace/js.js#11]
First, thanks for this great package!

## Introduction

Fibonacci example return wrong result when input greater than `45`.

## Recurrent

1. Run example both Native js and js.js with input `45`.
2. Run example both Native js and js.js with input `46`.

---
I tried to fix this issue myself, but source code is too huge to understand quickly, if anyone can give me a hint or idea about this issue, I am more than happy to help fix it!!

**Comment by jterrace** [comment]
Yeah, this is due to overflow I believe. I'm not sure how to fix it.
