### ISSUE TITLE
Feature request: remove requirement for window

### ISSUE THREAD

**Issue by zebMcCorkle** [jterrace/js.js#8]
I am trying to use `js.js` in Node, but it complains that `window` is missing.

By the way, I am using libjs-O2.min.js

EDIT: I also added the following to the bottom:

    module && module.exports = JSJS;

**Comment by jterrace** [comment]
Are you using node.js ?

**Comment by jterrace** [comment]
You should use libjs + js-js-wrapper, not js.js.
